In [14]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score


df= pd.read_csv('../titanic.csv', usecols=['Age', 'Pclass', 'Fare', 'Survived'])

In [15]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [16]:
df.isnull().mean()

Survived    0.000000
Pclass      0.000000
Age         0.198653
Fare        0.000000
dtype: float64

In [17]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [18]:
X_test, X_train, y_test, y_train = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
X_train.head()

     Pclass   Age     Fare
709       3   NaN  15.2458
439       2  31.0  10.5000
840       3  20.0   7.9250
720       2   6.0  33.0000
39        3  14.0  11.2417

In [40]:
knn = KNNImputer(n_neighbors=3, weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [41]:
pd.DataFrame(X_train_trf, columns=X_train.columns)

     Pclass       Age     Fare
0       3.0   9.00003  15.2458
1       2.0  31.00000  10.5000
2       3.0  20.00000   7.9250
3       2.0   6.00000  33.0000
4       3.0  14.00000  11.2417
..      ...       ...      ...
174     3.0  17.00000   7.1250
175     3.0  30.00000   7.2250
176     3.0  38.00000  31.3875
177     2.0  17.00000  10.5000
178     3.0   4.00000  16.7000

[179 rows x 3 columns]

In [42]:
lr = LogisticRegression()
lr.fit(X_train_trf, y_train)
y_pred = lr.predict(X_test_trf)
accuracy_score(y_test, y_pred)

0.6685393258426966

In [43]:
#cross validation accuracy
X_trf2 = knn.fit_transform(X)

np.mean(cross_val_score(lr,X_trf2, y, cv=10))

np.float64(0.7037702871410738)